[package]
name = "tarocoin"
version = "0.1.0"
authors = ["rawfalafel <ymori123@gmail.com>"]

[dependencies]
rand = "0.3"
secp256k1 = { git = "https://github.com/apoelstra/rust-secp256k1", rev = "d0dc0"  }
